public enum Layers { 
  ENEMY = 8, 
  PLAYER = 9,  
  PLAYER_DASHING = 10, 
  FLASK = 11, 
  NORMAL_ITEM = 12, 
  SATYR = 22,
  CYCLOPS = 23,
  PLAYER_COLLISION_TRIGGER = 24,
  REAPER = 26,
  WITCH = 27
};